#! bin/usr/python3.5

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def main():
    res = fib(4000000)
    print("Result:",res)
def fib(m):
    a,b =1,1
    res = 0
    run = True
    while a < m:
        a, b = b, a+b
        print("{} \n".format(a))
        if a%2 == 0 and a < 4000000: res = res+a
    return res

if __name__ == "__main__": main()